apiVersion: v1
data:
  newrelic.yml: "# This file configures the New Relic Agent.  New Relic monitors\r\n#
    Java applications with deep visibility and low overhead.  For more details and
    additional\r\n# configuration options visit https://docs.newrelic.com/docs/java/java-agent-configuration.\r\n#\r\n#
    This configuration file is custom generated for Mangirdas Judeikis\r\n#\r\n#
    This section is for settings common to all environments.\r\n# Do not add anything
    above this next line.\r\ncommon: &default_settings\r\n\r\n  # ==============================
    LICENSE KEY ===============================\r\n  # You must specify the license
    key associated with your New Relic\r\n  # account. For example, if your license
    key is 12345 use this:\r\n  # license_key: '12345'\r\n  # The key binds your Agent's
    data to your account in the New Relic service.\r\n  license_key: '12345'\r\n\r\n
    \ # Agent Enabled\r\n  # Use this setting to disable the agent instead of removing
    it from the startup command.\r\n  # Default is true.\r\n  agent_enabled: true\r\n\r\n
    \ # Set the name of your application as you'd like it show up in New Relic.\r\n
    \ # If enable_auto_app_naming is false, the agent reports all data to this application.\r\n
    \ # Otherwise, the agent reports only background tasks (transactions for non-web
    applications)\r\n  # to this application. To report data to more than one application
    \r\n  # (useful for rollup reporting), separate the application names with \";\".\r\n
    \ # For example, to report data to \"My Application\" and \"My Application 2\"
    use this:\r\n  # app_name: My Application;My Application 2\r\n  # This setting
    is required. Up to 3 different application names can be specified.\r\n  # The
    first application name must be unique.\r\n  app_name: _unknown_\r\n  \r\n  # To
    enable high security, set this property to true. When in high\r\n  # security
    mode, the agent will use SSL and obfuscated SQL. Additionally,\r\n  # request
    parameters and message parameters will not be sent to New Relic.\r\n  high_security:
    true\r\n\r\n  # Set to true to enable support for auto app naming.\r\n  # The
    name of each web app is detected automatically\r\n  # and the agent reports data
    separately for each one.\r\n  # This provides a finer-grained performance breakdown
    for\r\n  # web apps in New Relic.\r\n  # Default is false.\r\n  enable_auto_app_naming:
    false\r\n\r\n  # Set to true to enable component-based transaction naming.\r\n
    \ # Set to false to use the URI of a web request as the name of the transaction.\r\n
    \ # Default is true.\r\n  enable_auto_transaction_naming: true\r\n\r\n  # The
    agent uses its own log file to keep its logging\r\n  # separate from that of your
    application.  Specify the log level here.\r\n  # This setting is dynamic, so changes
    do not require restarting your application.\r\n  # The levels in increasing order
    of verboseness are:\r\n  #   off, severe, warning, info, fine, finer, finest\r\n
    \ # Default is info.\r\n  log_level: info\r\n\r\n  # Log all data sent to and
    from New Relic in plain text.\r\n  # This setting is dynamic, so changes do not
    require restarting your application.\r\n  # Default is false.\r\n  audit_mode:
    false\r\n\r\n  # The number of backup log files to save.\r\n  # Default is 1.\r\n
    \ log_file_count: 1\r\n\r\n  # The maximum number of kbytes to write to any one
    log file.\r\n  # The log_file_count must be set greater than 1.\r\n  # Default
    is 0 (no limit).\r\n  log_limit_in_kbytes: 0\r\n\r\n  # Override other log rolling
    configuration and roll the logs daily.\r\n  # Default is false.\r\n  log_daily:
    false\r\n\r\n  # The name of the log file.\r\n  # Default is newrelic_agent.log.\r\n
    \ log_file_name: newrelic_agent.log\r\n\r\n  # The log file directory.\r\n  #
    Default is the logs directory in the newrelic.jar parent directory.\r\n  #log_file_path:\r\n\r\n
    \ # The agent communicates with New Relic via https by\r\n  # default.  If you
    want to communicate with newrelic via http,\r\n  # then turn off SSL by setting
    this value to false.\r\n  # This work is done asynchronously to the threads that
    process your\r\n  # application code, so response times will not be directly affected\r\n
    \ # by this change.\r\n  # Default is true.\r\n  ssl: true\r\n\r\n  # Proxy settings
    for connecting to the New Relic server:\r\n  # If a proxy is used, the host setting
    is required.  Other settings\r\n  # are optional.  Default port is 8080.  The
    username and password\r\n  # settings will be used to authenticate to Basic Auth
    challenges\r\n  # from a proxy server.\r\n  #proxy_host: hostname\r\n  #proxy_port:
    8080\r\n  #proxy_user: username\r\n  #proxy_password: password\r\n\r\n  # Limits
    the number of lines to capture for each stack trace. \r\n  # Default is 30\r\n
    \ max_stack_trace_lines: 30\r\n\r\n  # Provides the ability to configure the attributes
    sent to New Relic. These\r\n  # attributes can be found in transaction traces,
    traced errors, Insight's \r\n  # transaction events, and Insight's page views.\r\n
    \ attributes:\r\n  \r\n    # When true, attributes will be sent to New Relic.
    The default is true.\r\n    enabled: true\r\n    \r\n    #A comma separated list
    of attribute keys whose values should \r\n    # be sent to New Relic.\r\n    #include:\r\n
    \   \r\n    # A comma separated list of attribute keys whose values should \r\n
    \   # not be sent to New Relic.\r\n    #exclude:\r\n    \r\n\r\n  # Transaction
    tracer captures deep information about slow\r\n  # transactions and sends this
    to the New Relic service once a\r\n  # minute. Included in the transaction is
    the exact call sequence of\r\n  # the transactions including any SQL statements
    issued.\r\n  transaction_tracer:\r\n\r\n    # Transaction tracer is enabled by
    default. Set this to false to turn it off.\r\n    # This feature is not available
    to Lite accounts and is automatically disabled.\r\n    # Default is true.\r\n
    \   enabled: true\r\n\r\n    # Threshold in seconds for when to collect a transaction\r\n
    \   # trace. When the response time of a controller action exceeds\r\n    # this
    threshold, a transaction trace will be recorded and sent to\r\n    # New Relic.
    Valid values are any float value, or (default) \"apdex_f\",\r\n    # which will
    use the threshold for the \"Frustrated\" Apdex level\r\n    # (greater than four
    times the apdex_t value).\r\n    # Default is apdex_f.\r\n    transaction_threshold:
    apdex_f\r\n\r\n    # When transaction tracer is on, SQL statements can optionally
    be\r\n    # recorded. The recorder has three modes, \"off\" which sends no\r\n
    \   # SQL, \"raw\" which sends the SQL statement in its original form,\r\n    #
    and \"obfuscated\", which strips out numeric and string literals.\r\n    # Default
    is obfuscated.\r\n    record_sql: obfuscated\r\n\r\n    # Set this to true to
    log SQL statements instead of recording them.\r\n    # SQL is logged using the
    record_sql mode.\r\n    # Default is false.\r\n    log_sql: false\r\n\r\n    #
    Threshold in seconds for when to collect stack trace for a SQL\r\n    # call.
    In other words, when SQL statements exceed this threshold,\r\n    # then capture
    and send to New Relic the current stack trace. This is\r\n    # helpful for pinpointing
    where long SQL calls originate from.\r\n    # Default is 0.5 seconds.\r\n    stack_trace_threshold:
    0.5\r\n\r\n    # Determines whether the agent will capture query plans for slow\r\n
    \   # SQL queries. Only supported for MySQL and PostgreSQL.\r\n    # Default is
    true.\r\n    explain_enabled: true\r\n\r\n    # Threshold for query execution
    time below which query plans will not \r\n    # not be captured.  Relevant only
    when `explain_enabled` is true.\r\n    # Default is 0.5 seconds.\r\n    explain_threshold:
    0.5\r\n\r\n    # Use this setting to control the variety of transaction traces.\r\n
    \   # The higher the setting, the greater the variety.\r\n    # Set this to 0
    to always report the slowest transaction trace.\r\n    # Default is 20.\r\n    top_n:
    20\r\n\r\n  # Error collector captures information about uncaught exceptions and\r\n
    \ # sends them to New Relic for viewing.\r\n  error_collector:\r\n\r\n    # This
    property enables the collection of errors. If the property is not\r\n    # set
    or the property is set to false, then errors will not be collected.\r\n    # Default
    is true.\r\n    enabled: true\r\n\r\n    # Use this property to exclude specific
    exceptions from being reported as errors\r\n    # by providing a comma separated
    list of full class names.\r\n    # The default is to exclude akka.actor.ActorKilledException.
    If you want to override\r\n    # this, you must provide any new value as an empty
    list is ignored.\r\n    ignore_errors: akka.actor.ActorKilledException\r\n\r\n
    \   # Use this property to exclude specific http status codes from being reported
    as errors\r\n    # by providing a comma separated list of status codes.\r\n    #
    The default is to exclude 404s. If you want to override\r\n    # this, you must
    provide any new value as an empty list is ignored.\r\n    ignore_status_codes:
    404\r\n\r\n  # Transaction Events are used for Histograms and Percentiles. Unaggregated
    data is collected\r\n  # for each web transaction and sent to the server on harvest.
    \r\n  transaction_events:\r\n\r\n    # Set to false to disable transaction events.\r\n
    \   # Default is true.\r\n    enabled: true\r\n\r\n    # Events are collected
    up to the configured amount. Afterwards, events are sampled to\r\n    # maintain
    an even distribution across the harvest cycle.\r\n    # Default is 2000.  Setting
    to 0 will disable.\r\n    max_samples_stored: 2000\r\n\r\n  # Cross Application
    Tracing adds request and response headers to\r\n  # external calls using supported
    HTTP libraries to provide better\r\n  # performance data when calling applications
    monitored by other New Relic Agents.\r\n  cross_application_tracer:\r\n\r\n    #
    Set to false to disable cross application tracing.\r\n    # Default is true.\r\n
    \   enabled: true\r\n\r\n  # Thread profiler measures wall clock time, CPU time,
    and method call counts\r\n  # in your application's threads as they run.\r\n  #
    This feature is not available to Lite accounts and is automatically disabled.\r\n
    \ thread_profiler:\r\n\r\n    # Set to false to disable the thread profiler.\r\n
    \   # Default is true.\r\n    enabled: true\r\n\r\n  # New Relic Real User Monitoring
    gives you insight into the performance real users are\r\n  # experiencing with
    your website. This is accomplished by measuring the time it takes for\r\n  # your
    users' browsers to download and render your web pages by injecting a small amount\r\n
    \ # of JavaScript code into the header and footer of each page. \r\n  browser_monitoring:\r\n\r\n
    \   # By default the agent automatically inserts API calls in compiled JSPs to\r\n
    \   # inject the monitoring JavaScript into web pages. Not all rendering engines
    are supported.\r\n    # See https://docs.newrelic.com/docs/java/real-user-monitoring-in-java#manual_instrumentation\r\n
    \   # for instructions to add these manually to your pages.\r\n    # Set this
    attribute to false to turn off this behavior.\r\n    auto_instrument: true\r\n\r\n
    \ class_transformer:\r\n    # This instrumentation reports the name of the user
    principal returned from \r\n    # HttpServletRequest.getUserPrincipal() when servlets
    and filters are invoked.\r\n    com.newrelic.instrumentation.servlet-user:\r\n
    \     enabled: false\r\n\r\n    com.newrelic.instrumentation.spring-aop-2:\r\n
    \     enabled: false\r\n\r\n  # User-configurable custom labels for this agent.
    \ Labels are name-value pairs.\r\n  # There is a maximum of 64 labels per agent.
    \ Names and values are limited to 255 characters.\r\n  # Names and values may
    not contain colons (:) or semicolons (;).\r\n  labels: {{LABELS}}\r\n\r\n    # An example label\r\n    #label_name: label_value\r\n\r\n\r\n#
    Application Environments\r\n# ------------------------------------------\r\n#
    Environment specific settings are in this section.\r\n# You can use the environment
    to override the default settings.\r\n# For example, to change the app_name setting.\r\n#
    Use -Dnewrelic.environment=<environment> on the Java startup command line\r\n#
    to set the environment.\r\n# The default environment is production.\r\n\r\n# NOTE
    if your application has other named environments, you should\r\n# provide configuration
    settings for these environments here.\r\n\r\ndevelopment:\r\n  <<: *default_settings\r\n
    \ app_name: My Application (Development)\r\n\r\ntest:\r\n  <<: *default_settings\r\n
    \ app_name: My Application (Test)\r\n\r\nproduction:\r\n  <<: *default_settings\r\n\r\nstaging:\r\n
    \ <<: *default_settings\r\n  app_name: My Application (Staging)\r\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: newrelic-config
